version: '3'
services:
  tensorflow-jupyter-tensorboard:
    image: "tensorflow/tensorflow:latest"
    volumes:
      - ./notebooks:/notebooks
      - ./data:/data
    ports:
      - 8888:8888
      - 6006:6006
